spring:
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
